### ISSUE TITLE
Tag a stable realease

### ISSUE THREAD

**Issue by mtangaro** [grycap/ansible-role-htcondor#17]
Hi all,
is it possible to tag a release version of the role? This will help for both EuroScienceGateway project, where we'd like to use it for pulsar deployments, and also for TOSCA types.

**Comment by sebastian-luna-valero** [comment]
Hi Marco,

Thanks for bringing this up.

Let's wait for @micafer 's opinion.

The current master branch is working well for me so I think tagging and releasing the last commit should be ok to start with.

Thanks,
Sebastian

**Comment by micafer** [comment]
I agree, I will make a first release with the current master version.

**Comment by mtangaro** [comment]
thank you both!

**Comment by micafer** [comment]
Version 1.0.0 released.

**Comment by sebastian-luna-valero** [comment]
Great, many thanks, Miguel.
